### PR TITLE
OCSSD 2.0, Mutex rewrite, Vertical mapping

### PR DESCRIPTION
**Pull request by niclashedam**
During my Bachelor's project, I continued the research and development of an instance of RocksDB on top of an Open-Channel SSD. Since my developments are relevant for further research, I thought I would make it available here. This pull request introduces the following new functionality:

**OCSSD 2.0 support**
I have ported the NVM environment to run on OCSSD 2.0. Most of these changes include replacing the units from OCSSD 1.2 to 2.0. RocksDB queries the device regarding the optimal number of sectors for writing using the `nvm_dev_get_ws_opt` function. Mind that I have not tested this on any other device than my development device (I think it is a CNEX Granby SSD).

**Vertical mapping**
I have introduced a new mapping method for storing data on the Open-Channel SSD. Vertical mapping creates blocks on the Open-Channel SSD that is limited to a single PU. This limitation should, on paper, decrease the interference, as RocksDB can alter multiple blocks at once in complete isolation. When setting the mapping method to vertical, the height of the blocks is defined as well. The preferences are set via the NVM URI.

**MutexLock optimisation**
During the development of vertical mapping, I discovered some inefficiencies related to the mutual exclusion locks in the NVM environment. The efficiencies would lock a block unnecessarily. The optimisation made sequential reads double in performance.

### CODE REVIEW

**Comment by javigon** [comment]
Hi Niclas,

Thanks for the PR. Let me review it in the following days. Since this is part of your Bachelor project, can you share the documentation too?

Also, have you tried to run this in qemu? It is easier to test different configurations there. I would recommend using Klaus' qemu, which is updated and ready for upstreaming. The current branch is v4 [1]

[1] https://github.com/birkelund/qemu/tree/ocssd/v4

Thanks,
Javier

**Comment by niclashedam** [comment]
I have not tried running it on qemu. I will try to do so when I have time.

I can send you the bachelor thesis for you to read. However, I need to incorporate the comments from the exam before it is ready to be publicly available.

**Comment by MatiasBjorling** [comment]
Hi Niclas,

Great work. I've pulled it in. If you like to send me a copy as well, I'll like to read your work. My e-mail is mb@lightnvm.io. Thank you!

Javier, feel free to submit pull request for fixes.

Kind regards,
Matias

**Comment by javigon** [comment]
Niclas,

You have my e-mail. You can send it after the exam.

See you around at ITU!

Javier

**Comment by niclashedam** [comment]
Cool. I will send you the report today or tomorrow. The exam was in May, but the comments and mistakes from the exam have not yet been incorporated, as the faith of the report is to be decided.

**Comment by javigon** [comment]
Thanks! 

Hehehe. Sounds good - sure it will go the right way.

**Pull request merged**
